In [ ]:
#Notebook 1 of 10 for tensorflow


In [3]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.18.0


In [4]:
#Creating Tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
matrix = tf.constant([[10,7], [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
another_matrix = tf.constant([[3.,10.] , [6.,9.] , [6.,3.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 3., 10.],
       [ 6.,  9.],
       [ 6.,  3.]], dtype=float16)>

In [ ]:
changeable_tensor = tf.Variable([4,14])
unchangeable_tensor = tf.constant([4,14])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 4, 14], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 4, 14], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(10)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([10, 14], dtype=int32)>

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = (3,2))
random_1
random_2
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
tf.random.shuffle(random_1, seed = 5)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ],
       [-0.7565803 , -0.06854702]], dtype=float32)>

In [ ]:
tf.ones(shape = (4,14))
numpy_A = np.arange(1,10, dtype=np.int32)
A = tf.constant(numpy_A)
B = tf.constant(numpy_A, shape = (3,3))
A, B

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>)

In [ ]:
rank4_tensor = tf.ones(shape = (4, 5, 6, 7,))


In [ ]:
rank4_tensor.shape, rank4_tensor.ndim, tf.size(rank4_tensor)

(TensorShape([4, 5, 6, 7]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=840>)

In [ ]:
#Get the first 2 elements of each dimensions
list = [1,2,3,4]
list[:2]
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10,7] , [3,4]])


In [ ]:
rank_3_tensor = rank_2_tensor[:,:, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis = -1, )

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis =1)


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
tensor = tf.constant([[4,14], [7,9]])

tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 24],
       [17, 19]], dtype=int32)>

In [ ]:
tf.matmul(tensor, tensor
          )
x = tf.constant([[2,4],[4,2],[5,5],
                 [9,1],[6,6],[8,6]])
y = tf.random.shuffle(x,seed= 9)

tf.reshape(y, shape = (6,2))
tf.transpose(x)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[2, 4, 5, 9, 6, 8],
       [4, 2, 5, 1, 6, 6]], dtype=int32)>

In [ ]:
tf.multiply(tensor, 10)
tf.divide(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 7. ],
       [3.5, 4.5]])>

In [ ]:
#Dot Product
x = tf.constant([[[8,9],[9,8],[4,14],[14,4]], [[4,4],[5,5],[6,6],[7,7]]])
y = tf.random.uniform(
    shape = (16,1),
    minval = 0,
    maxval=10,
    dtype = tf.int32
)
print(y)

tf.Tensor(
[[8]
 [7]
 [6]
 [9]
 [8]
 [9]
 [0]
 [0]
 [3]
 [2]
 [7]
 [9]
 [6]
 [6]
 [9]
 [2]], shape=(16, 1), dtype=int32)


In [ ]:

tf.transpose(x)
x =tf.reshape(x, (1,16))
z = tf.tensordot(x, y, 2)

In [ ]:
#Change data type
C = tf.constant([[2,1], [4,3]])
C.dtype
D = tf.constant ([[7.8,6],[5,8]])
D = tf.cast(D,dtype=tf.float16)
D.dtype
C = tf.cast(C, dtype=tf.int64)
C.dtype
E

NameError: name 'E' is not defined

**Aggregating Tensors**
ie. condensing tensors,

In [ ]:
#Get the absolute value
D = tf.constant([4,-14])
tf.abs(D)
E = tf.constant(np.random.randint(0,100, size = 64))
tf.size(E), E.shape, E.ndim
tf.reduce_min(E)


In [ ]:
tf.reduce_max(E)

In [ ]:
tf.reduce_mean(E)

In [ ]:
tf.reduce_sum(E)

In [ ]:
E = tf.cast(E, dtype = tf.float64)

E2 = tf.math.reduce_std(E)
E1 = tf.math.reduce_variance(E)
V = tf.random.uniform(shape=[50])
V

In [ ]:
#Positional max and mins of tensors
q = tf.argmax(V)
q2 = tf.argmin(V)


In [ ]:
V[tf.argmin(V)] == V[22]

In [ ]:
### squeezing a tensor, removing all single dimensions: create a tensor
tf.random.set_seed(41)
G = tf.constant(tf.random.uniform(shape=[35]), shape=(1,1,1,1,35))
G = tf.squeeze(G)
G

In [ ]:
###One-hot encoding: a value that exists as 1 for something and 0 for everything else, a form of numerical encoding.
list_example = [0,1,2,3] # red, green, blue, teal respectively
tf.one_hot(list_example, depth = 4) #extremely interesting, forms a matrix of basis vectors for 4d space

In [ ]:
#customizing values
tf.one_hot(list_example, depth = 4, on_value = "peepeepoopoo", off_value = "NiggaBalls")

In [ ]:
#More math functions; sqrt requires float
H = tf.range(1,10)
tf.square(H)
tf.sqrt(tf.cast(H, dtype = tf.float32))
tf.math.log(tf.cast(H, dtype = tf.float32)) #natural log, base e

TensorFlow interacts well with NumPy arrays.

In [ ]:
#Create tensor from a NumPy array
J = tf.constant(np.array([3.,4.,8.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 8.])>

In [ ]:
#convert back
np.array(J) , type(np.array(J))
J.numpy(), type(J.numpy()), J.numpy()[0]

(array([3., 4., 8.]), numpy.ndarray, 3.0)

In [ ]:
#The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,5.,7.]))
tensor_J = tf.constant([3.,5.,7.])

numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
#Regression analysis : In statsistical modeling , regression analysis is a set of statistical processes for estimating the relationships between a dependent variable (often called the outcome or response variable, or a label in machine learning parlance) and one or more error-free independent variables (often called regressors, predictors, covariates, explanatory variables or features). The most common form of regression analysis is linear regression, in which one finds the line (or a more complex linear combination) that most closely fits the data according to a specific mathematical criterion. For example, the method of ordinary least squares computes the unique line (or hyperplane) that minimizes the sum of squared differences between the true data and that line (or hyperplane). For specific mathematical reasons (see linear regression), this allows the researcher to estimate the conditional expectation (or population average value) of the dependent variable when the independent variables take on a given set of values. Less common forms of regression use slightly different procedures to estimate alternative location parameters (e.g., quantile regression or Necessary Condition Analysis[1]) or estimate the conditional expectation across a broader collection of non-linear models (e.g., nonparametric regression).

In [ ]:
J.shape

TensorShape([3])